language: node_js
cache: 
  directories: 
    - node_modules

node_js:
  - 'stable'

git:
  depth: 3

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: build/
  target-branch: master
  commit_message: "Deploy release ${TRAVIS_TAG}"
  on: 
    branch: develop